theme: jekyll-theme-minimal
title: Разбор алгоритмических задач от Сашули
description: Данная страничка содержит практический материал по решению алгоритмических задач, которые встречаются на собеседованиях в крупные (и не очень) IT компании.
logo: vinni.png
markdown: kramdown
kramdown:
  input: GFM
